#Adress the service will get deployed to. E.g. "myjira.test.linkyard.ch"
# Default: <release name>.test.linkyard.ch
#hostname: myjira.test.linkyard.ch


# Version of Jira Service Desk.
# see: https://hub.docker.com/r/cptactionhank/atlassian-jira-service-desk/tags/
jiraVersion: 3.2.7

## Specify a imagePullPolicy
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent


persistence:
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass: generic
  size: 10Gi


# Maximum Java Heap Space Memory (used with -Xmx)
maxHeap: 512m

## Configure resource requests
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 512Mi
    cpu: 100m


# Database configuration
postgresql:
  imageTag: "9.3.15"
  persistence:
    ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
    ## Default: volume.alpha.kubernetes.io/storage-class: default
    ##
    # storageClass: generic
    size: 1Gi