apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "postal.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: postal
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "postal.fullname" . }}
data:
  mariadbPassword: {{ .Values.mariadb.rootUser.password | b64enc | quote }}
  rabbitMqPassword: {{ .Values.rabbitmq.rabbitmqPassword | b64enc | quote }}
  rabbitMqManagementPassword: {{ .Values.rabbitmq.managementPassword | b64enc | quote }}
  railsSecretKey: {{ .Values.postal.railsSecretKey | b64enc | quote }}
  signingKey: {{ .Values.postal.signingKey | b64enc | quote }}
  letsEncryptKey: {{ .Values.postal.letsEncryptKey | b64enc | quote }}
  smtpPassword: {{ .Values.postal.smtpPassword | b64enc | quote }}
